#!/usr/bin/env bash
function cleanup {
  docker-compose kill
  docker-compose down -v
}
trap cleanup EXIT
# Run test
docker-compose build && docker-compose up -d && docker attach test_runner_1
# Show nginx-jwt logs after stopping it (valgrind result)
# docker-compose stop nginx-jwt &
# docker-compose logs -f nginx-jwt
